// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkcvqqaumfwyrkurfohh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rY3ZxcWF1bWZ3eXJrdXJmb2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NzgwNDQsImV4cCI6MjA1NjA1NDA0NH0.p0FFCB1r1kcAY3MrDKBuDbtwXLEcu0Y7QENSDa8xAjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);